### ISSUE TITLE
./entrypoint.sh: line 7: DOMAIN: unbound variable

### ISSUE THREAD

**Issue by newcharacteryigit** [notgiven688/webminerpool#151]
When I try to deploy my app to Heroku I'm getting "./entrypoint.sh: line 7: DOMAIN: unbound variable" error and the app not starting.

What can I do for solve this error?

**Comment by MexHigh** [comment]
I solved it by supplying an empty string to the `DOMAIN` envvar.

docker-compose example:

```
version: '3'
services:
  webminerpool:
    ...
    environment:
      DOMAIN: ""
...
```
